language: java
services: docker
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
  - secure: w5VfIJI0RC27fUcVC/tB63Z1IOIkFCz3khmrrBSMwDjmKFWEplnkm1Yhs379yqohsSHE18SqY4MgLzOu9KJShoP1cur9ozhta+osSjXOZpiES/fQyRLRrCDSQR0ZLX0MBubJIGysFJrlPmMuue9AhcNzOLR6wwYrmZr9mIWMQcc=
addons:
  ssh_known_hosts: 104.155.231.103
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip
install:
- pip install --user flake8
script:
- gradle build -x checkstyleTest -x checkstyleMain
- bin/start.sh
- flake8 bin
- docker build -t loklak_server .
- docker images
- docker run loklak_server bash /loklak_server/bin/start.sh -I
after_success:
- bash <(curl -s https://codecov.io/bash)
- gradle clean
- bash .utility/push-docker.sh
- bash kubernetes/bin/update-deployment-travis.sh
