language: java
services: docker
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
  - secure: w5VfIJI0RC27fUcVC/tB63Z1IOIkFCz3khmrrBSMwDjmKFWEplnkm1Yhs379yqohsSHE18SqY4MgLzOu9KJShoP1cur9ozhta+osSjXOZpiES/fQyRLRrCDSQR0ZLX0MBubJIGysFJrlPmMuue9AhcNzOLR6wwYrmZr9mIWMQcc=
addons:
  ssh_known_hosts: 104.155.231.103
install:
- pip install --user flake8
script:
- gradle build
- bin/start.sh
- flake8 bin
- docker build -t loklak_server .
- docker images
- docker run loklak_server bash /loklak_server/bin/start.sh -I
before_script:
- pip install --user codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn clean cobertura:cobertura coveralls:report
- codecov
before_deploy:
- openssl aes-256-cbc -K $encrypted_e0d8735ecce8_key -iv $encrypted_e0d8735ecce8_iv -in .utility/loklakserver.1.enc -out .utility/loklakserver.1 -d
- eval "$(ssh-agent -s)"
- chmod 600 .utility/loklakserver.1
- ssh-add .utility/loklakserver.1
deploy:
  - provider: script
    skip_cleanup: true
    script: ssh loklak@104.155.231.103 'bash -s' < .utility/deploy-loklak.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: .utility/push-docs-to-gh-pages.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: .utility/push-docs-to-gh-pages.sh
    on:
      branch: master
