apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: web
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - staging.loklak.org
    secretName: loklak-api-tls
  rules:
  - host: staging.loklak.org
    http:
      paths:
      - path: /
        backend:
          serviceName: server
          servicePort: 80
